services:
  base-chatbot:
    build:
      context: .
      dockerfile: src/telegram_llm_bot/bots/base_chatbot/Dockerfile
    command: poetry run telegram-llm-bot
    container_name: base-chatbot
    env_file:
      - .env
      - src/telegram_llm_bot/bots/base_chatbot/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: src/telegram_llm_bot/logs
        target: /app/src/telegram_llm_bot/logs
      - type: bind
        source: .tmp
        target: /app/.tmp
    restart: "no"
